// Demo genome session — injected when user triggers the demo
export const DEMO_GENOME_MESSAGES = [
  {
    role: 'user',
    content: 'I want to add a subscription system to VIGIL so users can pay monthly and get different access tiers',
    id: 'demo-user-1',
  },
  {
    role: 'assistant',
    content: 'Understood. Let me decode that properly.',
    id: 'demo-riley-1',
  },
  {
    role: 'genome',
    genome_type: 'founder_intent',
    id: 'demo-intent-1',
    genome_data: {
      raw_request: 'Add a subscription system to VIGIL so users can pay monthly and get different access tiers',
      interpreted_request: 'Implement a tiered membership system for VIGIL with Stripe billing and role-based feature gating',
      real_want: 'A scalable monetisation layer that converts VIGIL\'s free users into paying members without breaking the existing privacy-first experience',
      business_goal: 'Generate recurring revenue from VIGIL\'s growing user base',
      ux_goal: 'Make upgrading feel natural and worth it — not pushy',
      technical_goal: 'Stripe subscriptions + role-based access control on protected features',
      risk_level: 'Medium',
      recommended_build_mode: 'Strategic Upgrade',
      confidence: 88,
    },
  },
  {
    role: 'genome',
    genome_type: 'genome_snapshot',
    id: 'demo-genome-1',
    genome_data: {
      pages: ['Dashboard', 'ThreatMonitor', 'PrivacyAudit', 'Settings', 'Alerts'],
      components: ['ThreatCard', 'RiskMeter', 'AlertFeed', 'DeviceList', 'PrivacyScore'],
      entities: ['User', 'ThreatEvent', 'DeviceProfile', 'AlertConfig', 'AuditLog'],
      functions: ['scanNetwork', 'generateThreatReport', 'sendAlertEmail', 'analysePrivacyScore'],
      routes: ['/dashboard', '/monitor', '/audit', '/settings', '/alerts'],
      design_patterns: 'Dark glassmorphism, red/amber threat palette, mobile-first monitoring UI',
      user_journeys: 'Onboard → Connect devices → Monitor threats → Act on alerts → Review audit',
      revenue_paths: 'Currently none. Opportunity: Free tier (3 devices) → Pro tier ($12/mo, unlimited) → Business tier ($49/mo, team features)',
      risk_zones: 'Feature gating must not break existing users. Stripe webhook reliability is critical.',
      technical_debt: 'AlertConfig entity is overloaded — should be split into AlertRule and NotificationPrefs',
      strategic_opportunities: 'Subscription wall around ThreatReport generation and AI-powered PrivacyScore creates strong conversion pressure',
    },
  },
  {
    role: 'assistant',
    content: 'Here are three ways I can build this. Each has different speed, risk, and commercial upside.',
    id: 'demo-riley-2',
  },
  {
    role: 'genome',
    genome_type: 'build_simulation',
    id: 'demo-sim-1',
    genome_data: [
      {
        mode: 'Fast Patch',
        summary: 'Add a basic Stripe Checkout link, a "Pro" boolean on the User entity, and manually gate two features behind it. Fastest path to first dollar.',
        speed_score: 9,
        risk_score: 3,
        commercial_value_score: 5,
        user_value_score: 4,
        technical_debt_score: 7,
        base44_compatibility_score: 9,
        riley_pick: false,
        riley_recommendation: 'Gets you revenue in 2 hours but creates messy debt. Fine if you need proof of concept today.',
      },
      {
        mode: 'Strategic Upgrade',
        summary: 'Implement proper Stripe subscriptions with webhook automation, a Subscription entity, role-based feature gating, and a clean upgrade flow in the app.',
        speed_score: 6,
        risk_score: 5,
        commercial_value_score: 9,
        user_value_score: 8,
        technical_debt_score: 3,
        base44_compatibility_score: 8,
        riley_pick: true,
        riley_recommendation: 'This is the right move. Builds a real monetisation layer. Stripe backend function + entity upgrade + feature flags. Estimated 1–2 build sessions.',
      },
      {
        mode: 'Breakthrough Architecture',
        summary: 'Full subscription platform: multiple tiers, usage-based limits, team seats, billing portal, admin override, proration handling, and a dedicated billing dashboard page.',
        speed_score: 2,
        risk_score: 7,
        commercial_value_score: 10,
        user_value_score: 9,
        technical_debt_score: 1,
        base44_compatibility_score: 7,
        riley_pick: false,
        riley_recommendation: 'This is VIGIL v2. Build the Strategic Upgrade first. Come back to this once you have 50 paying users.',
      },
    ],
  },
  {
    role: 'genome',
    genome_type: 'patch_plan',
    id: 'demo-patch-1',
    genome_data: {
      build_objective: 'Add Stripe subscription billing with tiered access to VIGIL',
      affected_files: ['pages/Settings.jsx', 'components/layout/Sidebar.jsx', 'App.jsx'],
      affected_entities: ['User (add subscription_tier, stripe_customer_id)', 'New: Subscription entity'],
      affected_functions: ['New: stripeWebhook', 'New: createCheckoutSession', 'New: getSubscriptionStatus'],
      affected_routes: ['/billing', '/upgrade'],
      implementation_order: '1. Add Subscription entity\n2. Update User entity (add stripe fields)\n3. Create Stripe backend functions\n4. Build upgrade/billing page\n5. Add feature gates to gated components\n6. Test webhook locally → deploy',
      risks: 'Stripe webhook must be registered before going live. User entity changes may require data migration. Feature gates must default to OPEN for existing users.',
      rollback_plan: 'Subscription entity can be dropped. User entity fields are additive (no data loss). Feature gates default to open.',
      testing_plan: 'Test checkout flow in Stripe test mode. Test webhook receipt. Verify free vs pro feature access.',
      requires_approval: true,
      approved: false,
    },
  },
  {
    role: 'genome',
    genome_type: 'pitch_plan',
    id: 'demo-pitch-1',
    genome_data: {
      one_liner: 'VIGIL Pro — real-time threat intelligence for people who take their privacy seriously.',
      user_benefit: 'Unlimited device monitoring, AI-generated threat reports, and priority alerts — all for less than a coffee a week.',
      founder_benefit: 'Recurring revenue that compounds. First subscription turns VIGIL from a project into a product.',
      market_relevance: 'Digital privacy is no longer niche. Post-Snowden, post-Cambridge Analytica, post-everything — people will pay for real protection.',
      why_this_matters: 'VIGIL is the only privacy monitoring tool built with a soul. This subscription makes it sustainable.',
      customer_pitch: 'Right now you get the basics free. VIGIL Pro gives you the full picture — unlimited devices, weekly AI reports, instant threat alerts. Cancel any time.',
      partner_pitch: 'VIGIL Pro is the foundation for a B2B tier. We can white-label threat monitoring for your platform\'s users.',
      investor_pitch: 'VIGIL has strong organic retention. Subscription conversion gives us a clear MRR story and unit economics to support a Series A narrative.',
    },
  },
  {
    role: 'genome',
    genome_type: 'approval_gate',
    id: 'demo-approval-1',
    genome_data: {
      context: 'Ready to build the Strategic Upgrade — Stripe subscriptions + feature gating. This touches User entity and creates 3 new backend functions. Approve to proceed.',
    },
  },
];

export const DEMO_POST_BUILD_LEDGER = {
  role: 'genome',
  genome_type: 'emergence_ledger',
  id: 'demo-ledger-1',
  genome_data: {
    what_worked: 'Stripe webhook integration via Base44 backend function worked cleanly. Role-based gating on the Subscription entity was more elegant than a boolean flag on User.',
    what_failed: 'Initial Stripe test mode used a hardcoded price ID — had to parameterise it. Webhook signature verification needed async SubtleCrypto (not the sync Node version).',
    riley_learned: 'For any Stripe integration on Base44, always use constructEventAsync() not constructEvent(). Document this as a permanent rule.',
    reusable_pattern: 'Subscription entity + stripeWebhook function + role check hook — this is now a reusable pattern for any Base44 SaaS product.',
    future_recommendation: 'Next session: build the Billing Dashboard page and add usage-limit tracking to set up the Breakthrough Architecture tier for later.',
  },
};