// Ported from synthetix-ai/base44/functions/rileyAPIConnector/entry.ts
import { registerFunction } from '../registry.js';

/**
 * rileyAPIConnector — Generate integration code for any external API.
 * Input: { api_name, documentation_url, desired_actions, app_id }
 */

function isSafeExternalUrl(urlStr: string) {
  try {
    const url = new URL(urlStr);
    if (url.protocol !== 'http:' && url.protocol !== 'https:') return false;
    const host = url.hostname.toLowerCase();
    if (host === 'localhost' || host === '127.0.0.1' || host === '0.0.0.0' || host === '::1') return false;
    if (/^10\./.test(host)) return false;
    if (/^172\.(1[6-9]|2\d|3[01])\./.test(host)) return false;
    if (/^192\.168\./.test(host)) return false;
    if (/^169\.254\./.test(host)) return false;
    if (/^100\.(6[4-9]|[7-9]\d|1[01]\d|12[0-7])\./.test(host)) return false;
    if (/^0\./.test(host)) return false;
    if (host.startsWith('fc') || host.startsWith('fd') || host.startsWith('fe80')) return false;
    if (host === '169.254.169.254' || host.includes('metadata.google')) return false;
    return true;
  } catch { return false; }
}

registerFunction('rileyAPIConnector', async (req, res, base44) => {
  try {
    const user = await base44.auth.me();
    if (!user) {
      res.status(401).json({ error: 'Unauthorized' });
      return;
    }

    const { api_name, documentation_url, desired_actions = [], app_id } = req.body || {};
    if (!api_name) {
      res.status(400).json({ error: 'api_name is required' });
      return;
    }

    const apiKey = process.env.OPENROUTER_API_KEY || '';

    // Fetch docs if URL provided (SSRF-safe validation)
    let docsContext = '';
    if (documentation_url && isSafeExternalUrl(documentation_url)) {
      try {
        const docsRes = await fetch(documentation_url, { signal: AbortSignal.timeout(10000) });
        if (docsRes.ok) {
          const text = await docsRes.text();
          docsContext = `\nAPI Documentation (excerpt):\n${text.substring(0, 3000)}`;
        }
      } catch (_) {}
    }

    const actionsText = desired_actions.length > 0 ? desired_actions.join(', ') : 'list records, create record, get single record';

    const genPrompt = `Generate a complete Base44 backend function that integrates with the ${api_name} API.

Desired actions: ${actionsText}
${docsContext}

Base44 Deno function requirements (MANDATORY):
- Import: import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';
- Must use Deno.serve(async (req) => { ... }) wrapper
- Auth check: const base44 = createClientFromRequest(req); const user = await base44.auth.me();
- Secrets via Deno.env.get('ENV_VAR_NAME')
- Standard fetch() for HTTP calls
- Return Response.json({}) or new Response()
- Wrap everything in try/catch returning { error: error.message } on failure
- Log usage to CreditLedger entity: base44.asServiceRole.entities.CreditLedger.create({...})

Generate the complete, production-ready function code.

Return JSON only:
{
  "function_name": "integrate${api_name.replace(/[^a-zA-Z]/g, '')}",
  "function_code": "import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';\n...",
  "env_vars_needed": ["API_KEY_NAME"],
  "setup_instructions": "1. Set env var...",
  "test_payload": { "action": "list" }
}`;

    const genRes = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ model: 'anthropic/claude-3.5-sonnet', messages: [{ role: 'user', content: genPrompt }], max_tokens: 4000 }),
      signal: AbortSignal.timeout(60000),
    });
    const data: any = await genRes.json();
    if (data.error) throw new Error(data.error.message || JSON.stringify(data.error));

    const raw = data.choices[0].message.content;
    let generated: any;
    try {
      const match = raw.match(/\{[\s\S]*\}/);
      generated = JSON.parse(match ? match[0] : raw);
    } catch (_) {
      generated = { function_name: `integrate${api_name}`, function_code: raw, env_vars_needed: [], setup_instructions: '', test_payload: {} };
    }

    // Save APIIntegration record
    const integration: any = await base44.asServiceRole.entities.APIIntegration.create({
      name: api_name,
      provider: api_name,
      base_url: documentation_url || '',
      auth_type: 'api_key',
      auth_key_env_var: (generated.env_vars_needed || [])[0] || '',
      documentation_url: documentation_url || '',
      endpoints: JSON.stringify(desired_actions),
      status: 'configured',
      notes: `Auto-generated by rileyAPIConnector. Function: ${generated.function_name}`,
    }).catch(() => ({ id: null }));

    // Save as copy-ready BuilderPrompt
    const promptRecord: any = await base44.asServiceRole.entities.BuilderPrompt.create({
      title: `API Integration: ${api_name}`,
      content: `Create this backend function as functions/${generated.function_name}.js:\n\n\`\`\`javascript\n${generated.function_code}\n\`\`\`\n\nEnv vars needed: ${(generated.env_vars_needed || []).join(', ')}\n\nSetup: ${generated.setup_instructions}\n\nTest payload: ${JSON.stringify(generated.test_payload)}`,
      prompt_type: 'function',
      copy_ready: true,
      target_app_id: app_id || '',
      status: 'ready',
      notes: `Auto-generated by rileyAPIConnector for ${api_name}`,
    }).catch(() => ({ id: null }));

    res.json({
      api_integration_id: integration?.id || null,
      builder_prompt_id: promptRecord?.id || null,
      function_name: generated.function_name,
      env_vars_needed: generated.env_vars_needed || [],
      setup_instructions: generated.setup_instructions,
      test_payload: generated.test_payload,
    });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});
