// Ported from synthetix-ai/base44/functions/rileyAutoFollowUp/entry.ts
import { registerFunction } from '../registry.js';

/**
 * rileyAutoFollowUp — Scheduled function to check overdue follow-ups and generate drafts.
 * Input: {} — runs on schedule
 */

const FREQUENCY_DAYS: Record<string, number> = { weekly: 7, fortnightly: 14, monthly: 30, quarterly: 90, as_needed: 180, none: 9999 };

function addDays(dateStr: string, days: number) {
  const d = new Date(dateStr);
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}

registerFunction('rileyAutoFollowUp', async (req, res, base44) => {
  try {
    const user = await base44.auth.me();
    if (!user) {
      res.status(401).json({ error: 'Unauthorized' });
      return;
    }

    const apiKey = process.env.OPENROUTER_API_KEY || '';
    const today = new Date().toISOString().split('T')[0];

    // Read all contacts with follow-ups due
    const allContacts: any = await base44.asServiceRole.entities.RelationshipContact.list('-next_follow_up', 200);
    const overdue = allContacts.filter((c: any) =>
      c.follow_up_frequency !== 'none' &&
      c.next_follow_up &&
      c.next_follow_up <= today
    );

    let draftsGenerated = 0;
    let contactsUpdated = 0;

    for (const contact of overdue.slice(0, 15)) {
      // Get interaction history for context
      const [recentLogs, dealContext]: any[] = await Promise.all([
        base44.asServiceRole.entities.InteractionLog.filter({ contact_id: contact.id }, '-timestamp', 3).catch(() => []),
        contact.deal_pipeline_ids?.length > 0
          ? base44.asServiceRole.entities.DealPipeline.filter({ id: contact.deal_pipeline_ids[0] }, '-created_date', 1).catch(() => [])
          : Promise.resolve([]),
      ]);

      const lastLog = recentLogs[0];
      const deal = dealContext[0];

      // Generate personalised follow-up
      let draft: any = null;
      try {
        const prompt = `Generate a follow-up message for James Hatcher (Modern Mystic, Hermetica Holdings) to send to:

Name: ${contact.name}
Company: ${contact.company || 'Unknown'}
Role: ${contact.role || 'Unknown'}
Relationship type: ${contact.relationship_type}
Warmth level: ${contact.warmth}
Last interaction: ${lastLog?.summary || 'No recent interaction on record'}
Last contact date: ${contact.last_contact_date || 'Unknown'}
${deal ? `Active deal: ${deal.deal_name || ''} — stage: ${deal.stage || ''}` : ''}
Interests: ${(contact.interests || []).join(', ') || 'Unknown'}

The follow-up message should:
- Reference the last interaction specifically (not generic "checking in")
- Add genuine value — share an insight, resource, or relevant news
- Include a soft, appropriate CTA for their relationship stage
- Sound warm and human — James's voice, slightly mystical/visionary
- Be 3-5 sentences maximum

Return JSON only:
{ "subject": "...", "message": "...", "channel": "email", "cta_type": "meeting/reply/resource" }`;

        const r = await fetch('https://openrouter.ai/api/v1/chat/completions', {
          method: 'POST',
          headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
          body: JSON.stringify({ model: 'deepseek/deepseek-chat', messages: [{ role: 'user', content: prompt }], max_tokens: 500 }),
          signal: AbortSignal.timeout(20000),
        });
        const data: any = await r.json();
        const raw = data.choices?.[0]?.message?.content || '';
        const match = raw.match(/\{[\s\S]*\}/);
        draft = JSON.parse(match ? match[0] : raw);
      } catch (_) {
        draft = { subject: `Catching up — ${contact.name}`, message: `Hi ${contact.name}, it's been a while — hope you're well. I'd love to reconnect and hear what you're working on. Would you be open to a quick call this month? — James`, channel: 'email' };
      }

      // Save as ContentPiece draft (never auto-sends)
      await base44.asServiceRole.entities.ContentPiece.create({
        title: `Follow-up Draft: ${contact.name} — ${today}`,
        content: `To: ${contact.email || contact.name}\nSubject: ${draft.subject || ''}\nChannel: ${draft.channel || 'email'}\n\n${draft.message}`,
        content_type: 'email',
        status: 'draft',
        tags: ['follow_up', 'draft', contact.relationship_type || 'contact'],
        notes: `Auto-generated by rileyAutoFollowUp. Contact: ${contact.id}. Approved_by_james required before sending.`,
      }).catch(() => {});

      // Log as InteractionLog
      await base44.asServiceRole.entities.InteractionLog.create({
        contact_id: contact.id,
        interaction_type: 'email_sent',
        summary: `Follow-up draft generated: "${draft.subject || 'Follow up'}"`,
        sentiment: 'neutral',
        follow_up_needed: false,
        timestamp: new Date().toISOString(),
        notes: 'Draft only — not yet sent. Awaiting James approval.',
      }).catch(() => {});

      // Update next follow-up date
      const freqDays = FREQUENCY_DAYS[contact.follow_up_frequency] || 30;
      await base44.asServiceRole.entities.RelationshipContact.update(contact.id, {
        next_follow_up: addDays(today, freqDays),
      }).catch(() => {});

      draftsGenerated++;
      contactsUpdated++;
    }

    // Create IntelligenceReport summary
    if (overdue.length > 0) {
      await base44.asServiceRole.entities.IntelligenceReport.create({
        title: `Follow-Up Summary — ${today}`,
        report_type: 'daily_digest',
        summary: `${overdue.length} contacts had overdue follow-ups. ${draftsGenerated} drafts generated. All require James approval before sending.`,
        relevance_score: 75,
        urgency: overdue.length > 10 ? 'act_soon' : 'monitor',
        action_items: JSON.stringify(overdue.slice(0, 5).map((c: any) => `Follow up with ${c.name} (${c.company}) — ${c.warmth}`)),
        auto_generated: true,
        james_read: false,
        tags: ['follow_up', 'crm', 'automated'],
      }).catch(() => {});
    }

    res.json({
      overdue_count: overdue.length,
      drafts_generated: draftsGenerated,
      contacts_updated: contactsUpdated,
      note: 'All drafts saved as ContentPiece — never auto-sent. Require approved_by_james.',
    });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});
