// Ported from synthetix-ai/base44/functions/rileyAutoAudit/entry.ts
import { registerFunction } from '../registry.js';
import type { Base44Compat } from '../../../base44Compat.js';

/**
 * rileyAutoAudit — Auto-QA after asset generation.
 * Input: { asset_type, asset_id, app_build_id, project_id }
 * asset_type: "content" | "landing_page" | "pdf" | "image" | "video" | "agent" | "campaign"
 */

const AUDIT_CRITERIA: Record<string, { checks: string[]; min_word_count?: number }> = {
  content: {
    checks: ['has_title', 'has_body', 'word_count_ok', 'has_tags', 'status_set'],
    min_word_count: 100,
  },
  landing_page: {
    checks: ['has_title', 'has_body', 'has_meta', 'has_cta'],
    min_word_count: 200,
  },
  pdf: {
    checks: ['has_title', 'has_body'],
    min_word_count: 50,
  },
  image: {
    checks: ['has_url', 'has_prompt'],
  },
  video: {
    checks: ['has_url', 'has_prompt'],
  },
  agent: {
    checks: ['has_name', 'has_instructions', 'has_entities'],
  },
  campaign: {
    checks: ['has_title', 'has_body'],
    min_word_count: 50,
  },
};

async function auditContentPiece(base44: Base44Compat, asset_id: string, criteria: any) {
  const item: any = await base44.asServiceRole.entities.ContentPiece.filter({ id: asset_id }, '-created_date', 1);
  const record = item[0];
  if (!record) return { pass: false, issues: ['Record not found'] };

  const issues: string[] = [];
  if (criteria.checks.includes('has_title') && !record.title) issues.push('Missing title');
  if (criteria.checks.includes('has_body') && !record.body) issues.push('Missing body content');
  if (criteria.checks.includes('has_tags') && (!record.tags || record.tags.length === 0)) issues.push('No tags set');
  if (criteria.checks.includes('status_set') && !record.status) issues.push('No status set');
  if (criteria.min_word_count) {
    const wc = (record.body || '').split(/\s+/).filter(Boolean).length;
    if (wc < criteria.min_word_count) issues.push(`Word count ${wc} below minimum ${criteria.min_word_count}`);
  }
  return { pass: issues.length === 0, issues, record_title: record.title };
}

async function auditLandingPage(base44: Base44Compat, asset_id: string, criteria: any) {
  const items: any = await base44.asServiceRole.entities.LandingPage.filter({ id: asset_id }, '-created_date', 1);
  const record = items[0];
  if (!record) return { pass: false, issues: ['Record not found'] };

  const issues: string[] = [];
  if (!record.title) issues.push('Missing title');
  if (!record.body && !record.html_content) issues.push('Missing body/HTML content');
  if (!record.meta_description) issues.push('Missing meta description');
  return { pass: issues.length === 0, issues, record_title: record.title };
}

async function auditMediaAsset(base44: Base44Compat, asset_id: string) {
  const items: any = await base44.asServiceRole.entities.MediaAsset.filter({ id: asset_id }, '-created_date', 1);
  const record = items[0];
  if (!record) return { pass: false, issues: ['Record not found'] };

  const issues: string[] = [];
  if (!record.file_url && !record.url) issues.push('Missing asset URL');
  if (!record.prompt && !record.title) issues.push('Missing prompt or title');
  return { pass: issues.length === 0, issues, record_title: record.title || record.prompt };
}

registerFunction('rileyAutoAudit', async (req, res, base44) => {
  try {
    const user = await base44.auth.me();
    if (!user) {
      res.status(401).json({ error: 'Unauthorized' });
      return;
    }

    const { asset_type, asset_id, app_build_id, project_id } = req.body || {};
    if (!asset_type || !asset_id) {
      res.status(400).json({ error: 'asset_type and asset_id are required' });
      return;
    }

    const criteria = AUDIT_CRITERIA[asset_type] || { checks: ['has_title'] };
    let auditResult: any = { pass: false, issues: ['Unknown asset type'] };

    if (['content', 'landing_page_content', 'pdf', 'campaign'].includes(asset_type)) {
      auditResult = await auditContentPiece(base44, asset_id, criteria);
    } else if (asset_type === 'landing_page') {
      auditResult = await auditLandingPage(base44, asset_id, criteria);
    } else if (['image', 'video'].includes(asset_type)) {
      auditResult = await auditMediaAsset(base44, asset_id);
    } else {
      auditResult = { pass: true, issues: [], note: 'No specific audit criteria — manual review recommended' };
    }

    // Save QA Review record
    const qa: any = await base44.asServiceRole.entities.QAReview.create({
      title: `Auto-Audit: ${asset_type} — ${asset_id}`,
      app_build_id: app_build_id || '',
      project_id: project_id || '',
      frontend_status: auditResult.pass ? 'Pass' : 'Fail',
      notes: `Asset type: ${asset_type}. Issues: ${auditResult.issues?.join('; ') || 'None'}. Auto-generated by rileyAutoAudit.`,
    });

    // Log to ActivityLog
    await base44.asServiceRole.entities.ActivityLog.create({
      event_type: 'auto_audit',
      actor: 'Riley',
      summary: `Auto-audit ${auditResult.pass ? 'PASSED' : 'FAILED'} for ${asset_type} (${asset_id}): ${auditResult.issues?.join(', ') || 'All checks passed'}`,
      severity: auditResult.pass ? 'Info' : 'Warning',
      timestamp: new Date().toISOString(),
    });

    res.json({ ...auditResult, qa_review_id: qa.id });
    return;
  } catch (error: any) {
    res.status(500).json({ error: error.message });
    return;
  }
});
