// Ported from synthetix-ai/base44/functions/rileyCalendarConnect/entry.ts
import { registerFunction } from '../registry.js';

/**
 * rileyCalendarConnect — Manage James's calendar — availability, events, scheduling.
 * Input: { action, data }
 */

const AEST_OFFSET = 10; // hours ahead of UTC

function toISOWithOffset(dateStr: string, hour: number, minute = 0) {
  const d = new Date(dateStr);
  d.setUTCHours(hour - AEST_OFFSET, minute, 0, 0);
  return d.toISOString();
}

function generateFallbackSlots(durationMinutes = 60, preferredTime = 'any') {
  const slots = [];
  const now = new Date();
  for (let dayOffset = 1; dayOffset <= 7; dayOffset++) {
    const date = new Date(now);
    date.setDate(date.getDate() + dayOffset);
    if (date.getDay() === 0 || date.getDay() === 6) continue; // skip weekends

    const dateStr = date.toISOString().split('T')[0];
    const times = preferredTime === 'morning'
      ? [[9, 0], [10, 0], [11, 0]]
      : preferredTime === 'afternoon'
        ? [[13, 0], [14, 0], [15, 0]]
        : [[9, 0], [10, 0], [13, 0], [14, 0]];

    for (const [h, m] of times) {
      slots.push({
        date: dateStr,
        start: `${dateStr}T${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:00+10:00`,
        end: `${dateStr}T${String(h + Math.floor(durationMinutes / 60)).padStart(2, '0')}:${String((m + durationMinutes % 60) % 60).padStart(2, '0')}:00+10:00`,
        timezone: 'Australia/Sydney',
      });
    }
    if (slots.length >= 6) break;
  }
  return slots;
}

async function gcalRequest(method: string, path: string, data: any, apiKey: string) {
  const base = 'https://www.googleapis.com/calendar/v3';
  const url = method === 'GET' && data
    ? `${base}${path}?${new URLSearchParams(data).toString()}`
    : `${base}${path}`;
  const options: any = {
    method,
    headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
    signal: AbortSignal.timeout(20000),
  };
  if (data && method !== 'GET') options.body = JSON.stringify(data);
  const res = await fetch(url, options);
  return await res.json();
}

registerFunction('rileyCalendarConnect', async (req, res, base44) => {
  try {
    const user = await base44.auth.me();
    if (!user) {
      res.status(401).json({ error: 'Unauthorized' });
      return;
    }

    const { action, data = {} } = req.body || {};
    if (!action) {
      res.status(400).json({ error: 'action is required' });
      return;
    }

    const gcalKey = process.env.GOOGLE_CALENDAR_API_KEY || '';
    const calendlyKey = process.env.CALENDLY_API_KEY || '';

    const { date_range, event_title, event_description, duration_minutes = 60, attendees = [], preferred_times = 'any' } = data;

    // Fallback mode if no API key
    if (!gcalKey && !calendlyKey) {
      const slots = generateFallbackSlots(duration_minutes, preferred_times);
      if (action === 'find_slot' || action === 'check_availability') {
        res.json({
          available_slots: slots,
          event_created: null,
          scheduling_link: null,
          fallback_mode: true,
          message: 'No calendar API configured. Suggested AEST business hours slots generated.',
        });
        return;
      }
      // For create_event / list_upcoming — save as ContentPiece
      if (action === 'create_event') {
        const piece: any = await base44.asServiceRole.entities.ContentPiece.create({
          title: `Meeting Request: ${event_title || 'New Meeting'}`,
          content: `**Title:** ${event_title}\n**Description:** ${event_description || ''}\n**Duration:** ${duration_minutes} minutes\n**Attendees:** ${attendees.join(', ')}\n**Suggested slots:**\n${slots.slice(0, 3).map((s) => `- ${s.start}`).join('\n')}`,
          content_type: 'article',
          status: 'draft',
          tags: ['calendar', 'meeting_request'],
          notes: 'Auto-generated by rileyCalendarConnect — manual scheduling required',
        }).catch(() => ({ id: null }));
        res.json({ event_created: false, fallback_mode: true, content_piece_id: piece.id, suggested_slots: slots.slice(0, 3), message: 'Calendar API not configured. Meeting request saved for manual scheduling.' });
        return;
      }
      res.json({ available_slots: slots, fallback_mode: true });
      return;
    }

    // Calendly path
    if (calendlyKey && !gcalKey) {
      if (action === 'list_upcoming') {
        const start = new Date().toISOString();
        const end = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();
        const calendlyRes = await fetch(`https://api.calendly.com/scheduled_events?min_start_time=${start}&max_start_time=${end}`, {
          headers: { 'Authorization': `Bearer ${calendlyKey}` },
          signal: AbortSignal.timeout(15000),
        });
        const json: any = await calendlyRes.json();
        res.json({ available_slots: [], events: json.collection || [], scheduling_link: null });
        return;
      }
      res.json({ scheduling_link: `https://calendly.com`, available_slots: [], event_created: null, message: 'Use Calendly scheduling link for booking.' });
      return;
    }

    // Google Calendar path
    if (action === 'list_upcoming') {
      const timeMin = new Date().toISOString();
      const timeMax = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();
      const events: any = await gcalRequest('GET', '/calendars/primary/events', { timeMin, timeMax, singleEvents: true, orderBy: 'startTime', maxResults: 20 }, gcalKey);
      res.json({ events: events.items || [], available_slots: [], event_created: null, scheduling_link: null });
      return;
    }

    if (action === 'check_availability' || action === 'find_slot') {
      const timeMin = date_range?.start || new Date().toISOString();
      const timeMax = date_range?.end || new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();
      const events: any = await gcalRequest('GET', '/calendars/primary/events', { timeMin, timeMax, singleEvents: true, orderBy: 'startTime' }, gcalKey);
      const busyTimes = (events.items || []).map((e: any) => ({ start: e.start?.dateTime, end: e.end?.dateTime }));
      const fallbackSlots = generateFallbackSlots(duration_minutes, preferred_times);
      const freeSlots = fallbackSlots.filter((slot) => !busyTimes.some((busy: any) => busy.start <= slot.start && busy.end >= slot.end));
      res.json({ available_slots: freeSlots, busy_times: busyTimes, event_created: null, scheduling_link: null });
      return;
    }

    if (action === 'create_event') {
      const startTime = date_range?.start || toISOWithOffset(new Date().toISOString().split('T')[0], 9);
      const endTime = date_range?.end || new Date(new Date(startTime).getTime() + duration_minutes * 60000).toISOString();
      const eventBody = {
        summary: event_title || 'Meeting',
        description: event_description || '',
        start: { dateTime: startTime, timeZone: 'Australia/Sydney' },
        end: { dateTime: endTime, timeZone: 'Australia/Sydney' },
        attendees: attendees.map((email: string) => ({ email })),
      };
      const created: any = await gcalRequest('POST', '/calendars/primary/events', eventBody, gcalKey);
      res.json({ event_created: !!created.id, event: created, available_slots: [], scheduling_link: created.htmlLink || null });
      return;
    }

    res.status(400).json({ error: `Unknown action: ${action}` });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});
