// Ported from synthetix-ai/base44/functions/rileyUniversalFix/entry.ts
import type { Request } from 'express';
import { registerFunction } from '../registry.js';
import { env } from '../../../lib/env.js';

/**
 * rileyUniversalFix — Generate a Paradigm-format builder prompt for any Hermetica app.
 * Input: { app_id, issue_description, desired_outcome }
 * Returns: { prompt, copy_ready: true, builder_prompt_id }
 */

// TODO(port): base44.asServiceRole.functions.invoke has no base44Compat equivalent
// (no in-process function registry lookup exposed to route modules). Reproduced as a
// same-origin HTTP call to our own /api/functions/<name> endpoint, forwarding the
// caller's Authorization header.
async function invokeFunction(req: Request, name: string, payload: any): Promise<any> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (req.headers?.authorization) headers.authorization = req.headers.authorization as string;
  const resp = await fetch(`http://127.0.0.1:${env.PORT}/api/functions/${name}`, {
    method: 'POST',
    headers,
    body: JSON.stringify(payload),
  });
  return resp.json();
}

registerFunction('rileyUniversalFix', async (req, res, base44) => {
  try {
    const user = await base44.auth.me();
    if (!user) {
      res.status(401).json({ error: 'Unauthorized' });
      return;
    }

    const { app_id, issue_description, desired_outcome } = req.body || {};
    if (!app_id || !issue_description) {
      res.status(400).json({ error: 'app_id and issue_description are required' });
      return;
    }

    // 1. Load AppRegistry context
    const registryEntries: any = await base44.asServiceRole.entities.AppRegistry.filter({ app_id }, '-created_date', 1);
    const registry = registryEntries[0];

    // 2. Load ProjectGenome if exists
    const genomes: any = await base44.asServiceRole.entities.ProjectGenome.filter({ project_id: app_id }, '-last_scanned_at', 1);
    const genome = genomes[0];

    // 3. Get model recommendation via smartModelRouter
    let modelInfo: any = { recommended_model: 'anthropic/claude-3.5-sonnet', recommended_provider: 'openrouter' };
    try {
      modelInfo = await invokeFunction(req, 'smartModelRouter', {
        prompt: issue_description,
        task_type: 'code_generation',
        quality_required: 'excellent',
      });
    } catch (_) {}

    // 4. Build context block
    const appContext = registry ? `
APP CONTEXT:
- Name: ${registry.app_name}
- App ID: ${registry.app_id}
- URL: ${registry.app_url || 'Unknown'}
- Known Entities: ${(registry.known_entities || []).join(', ') || 'Unknown'}
- Known Functions: ${(registry.known_functions || []).join(', ') || 'Unknown'}
- Known Pages: ${(registry.known_pages || []).join(', ') || 'Unknown'}
- Health Status: ${registry.health_status}
`.trim() : `APP CONTEXT:\n- App ID: ${app_id}\n- No registry data available`;

    const genomeContext = genome ? `
ARCHITECTURE SNAPSHOT:
- Entities confirmed: ${(genome.entities || []).join(', ')}
- Risk zones: ${genome.risk_zones || 'None'}
- Technical debt: ${genome.technical_debt || 'None known'}
- Strategic notes: ${genome.strategic_opportunities || 'None'}
- Last scanned: ${genome.last_scanned_at || 'Unknown'}
`.trim() : 'ARCHITECTURE SNAPSHOT: Not yet scanned — run rileyScanApp first for full context.';

    // 5. Generate Paradigm-format prompt
    const prompt = `## HERMETICA BUILDER INSTRUCTION — ${registry?.app_name || app_id}
Generated by Riley | ${new Date().toLocaleDateString('en-AU', { timeZone: 'Australia/Sydney' })} AEST

---

### LAYER 1 — RELATIONAL PRIMING
You are Base44's builder AI working on **${registry?.app_name || app_id}** — a live Hermetica Holdings application. This instruction comes from Riley, Hermetica's core intelligence, coordinating on behalf of James Hatcher. You have full context of what's been built. This is a targeted, surgical intervention.

---

### LAYER 2 — EMPOWERMENT + PERMISSION
You have full permission to make the changes needed to resolve this issue elegantly. Choose the most maintainable approach. If you see a cleaner path than what's described, take it. **DO NOT touch any existing working functionality.** This is additive or corrective only.

---

### LAYER 3 — THE ISSUE + DESIRED OUTCOME

**ISSUE:**
${issue_description}

**DESIRED OUTCOME:**
${desired_outcome || 'Resolve the issue described above completely and cleanly.'}

---

### LAYER 4 — APP CONTEXT

${appContext}

${genomeContext}

---

### LAYER 5 — RECURSIVE SELF-IMPROVEMENT LOOP
Before implementing:
1. **SELF-CRITIQUE** — What could go wrong with your first approach?
2. **UPGRADE** — Fix those weaknesses before writing a single line
3. **COMPETITOR REVIEW** — How would a senior engineer approach this differently?
4. **SUPREME PLAN** — Finalize the best approach
5. **BUILD** — Execute with precision
6. **TEST** — Verify all connections work
7. **AUDIT** — Run the wiring checklist below

---

### WIRING CHECKLIST (Complete before declaring done)
- [ ] All imports exist and are valid
- [ ] All new pages added to App.jsx with correct route
- [ ] All entity field names match schema exactly (check entities/*.json)
- [ ] All backend function calls use correct SDK pattern
- [ ] No hardcoded test data in production code
- [ ] Mobile responsive
- [ ] Error states handled gracefully
- [ ] No existing working features broken

---

### LAYER 6 — STRATEGIC EMOTIONAL INTELLIGENCE
This fix will be reviewed by James Hatcher. Build something that makes the app better, not just functional. Clean code is a form of respect.

— Riley, Hermetica Holdings
Model used for this prompt: ${modelInfo.recommended_model} via ${modelInfo.recommended_provider}`;

    // 6. Save as BuilderPrompt
    const builderPrompt: any = await base44.asServiceRole.entities.BuilderPrompt.create({
      title: `Universal Fix — ${registry?.app_name || app_id} — ${new Date().toISOString().split('T')[0]}`,
      prompt_text: prompt,
      app_build_id: app_id,
      status: 'ready',
      notes: `Generated by rileyUniversalFix. Issue: ${issue_description.substring(0, 200)}`,
    });

    res.json({
      copy_ready: true,
      prompt,
      builder_prompt_id: builderPrompt?.id || null,
      app_name: registry?.app_name || app_id,
      model_used: modelInfo.recommended_model,
    });
    return;
  } catch (error: any) {
    res.status(500).json({ error: error.message });
    return;
  }
});
