// Ported from synthetix-ai/base44/functions/rileyDocGenerator/entry.ts
import { registerFunction } from '../registry.js';

/**
 * rileyDocGenerator — Auto-generate documentation for any Hermetica app.
 * Input: { app_id, doc_type }
 * doc_type: "api_docs" | "user_guide" | "developer_guide" | "entity_reference" | "full"
 */

registerFunction('rileyDocGenerator', async (req, res, base44) => {
  try {
    const user = await base44.auth.me();
    if (!user) {
      res.status(401).json({ error: 'Unauthorized' });
      return;
    }

    const { app_id, doc_type = 'developer_guide' } = req.body || {};
    if (!app_id) {
      res.status(400).json({ error: 'app_id is required' });
      return;
    }

    const apiKey = process.env.OPENROUTER_API_KEY || '';

    // Read AppRegistry
    const apps: any = await base44.asServiceRole.entities.AppRegistry.filter({ app_id }, '-created_date', 1);
    const appRecord: any = apps[0] || null;
    const app_name = appRecord?.app_name || app_id;
    const entities = appRecord?.known_entities || [];
    const functions = appRecord?.known_functions || [];
    const pages = appRecord?.known_pages || [];

    // Read ProjectGenome for richer context
    let genome: any = null;
    const genomes: any = await base44.asServiceRole.entities.ProjectGenome.filter({ project_id: app_id }, '-created_date', 1).catch(() => []);
    if (genomes.length > 0) genome = genomes[0];

    const docPrompt = `Generate ${doc_type} documentation for this Base44 application.

App Name: ${app_name}
App URL: ${appRecord?.app_url || 'Not configured'}
Entities: ${entities.length > 0 ? entities.join(', ') : 'None on record'}
Backend Functions: ${functions.length > 0 ? functions.join(', ') : 'None on record'}
Pages: ${pages.length > 0 ? pages.join(', ') : genome?.pages?.join(', ') || 'None on record'}
${genome?.user_journeys ? `User Journeys: ${genome.user_journeys}` : ''}
${genome?.revenue_paths ? `Revenue Paths: ${genome.revenue_paths}` : ''}

Documentation type: ${doc_type}

Doc type guidance:
- api_docs: Focus on backend functions — input/output, authentication, error codes, curl examples
- user_guide: Step-by-step guides for end users, screenshots placeholders, FAQs
- developer_guide: Technical setup, entity relationships, function architecture, deployment
- entity_reference: Full table of all entities with field types, enums, RLS rules
- full: Include all sections above

Format as clean Markdown with:
- Table of contents (with anchor links)
- Clear section headings (H2/H3)
- Entity reference tables (field | type | required | description)
- Function reference with input/output schemas
- Common workflow examples
- Error handling guide
- Code examples (JS/curl where applicable)

Write comprehensive, production-quality documentation. Be thorough.`;

    const r = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ model: 'anthropic/claude-3.5-sonnet', messages: [{ role: 'user', content: docPrompt }], max_tokens: 6000 }),
      signal: AbortSignal.timeout(90000),
    });
    const data: any = await r.json();
    if (data.error) throw new Error(data.error.message || JSON.stringify(data.error));

    const docContent = data.choices[0].message.content;
    const wordCount = docContent.split(/\s+/).length;
    const sections = (docContent.match(/^#{1,2} .+/gm) || []).length;

    // Save as ContentPiece
    const contentRecord: any = await base44.asServiceRole.entities.ContentPiece.create({
      title: `${app_name} — ${doc_type.replace(/_/g, ' ').replace(/\b\w/g, (l: string) => l.toUpperCase())}`,
      content: docContent,
      content_type: 'article',
      status: 'published',
      tags: ['documentation', doc_type, app_name.toLowerCase().replace(/\s+/g, '-')],
      notes: `Auto-generated by rileyDocGenerator. ${wordCount} words, ${sections} sections.`,
    }).catch(() => ({ id: null }));

    res.json({
      content_id: contentRecord?.id || null,
      app_name,
      doc_type,
      word_count: wordCount,
      sections_generated: sections,
      preview: docContent.substring(0, 500) + '...',
    });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});
